title: Semantic Segmentation with Masks
type: community
group: Vision Analytics
order: 2
image: /static/templates/semantic-segmentation-masks.png
details: <h1>Draw masks around the object with the brush tool</h1>
config: |
  <View>
    <Image name="image" value="$image" zoom="true"/>
    <BrushLabels name="tag" toName="image">
      <Label value="Airplane" background="rgba(255, 0, 0, 0.7)"/>
      <Label value="Car" background="rgba(0, 0, 255, 0.7)"/>
    </BrushLabels>
  </View>

