title: Detection
type: community
group: Vision Analytics
order: 2
image: /static/templates/object-detection.png
details: <h1>Draw a bounding box around the object</h1>
config: |
  <View>
    <Image name="image" value="$image"/>
    <RectangleLabels name="label" toName="image">
      <Label value="Cat" background="skyblue"/>
      <Label value="Dog" background="yellow"/>
    </RectangleLabels>
  </View>
